prevent exception when destroying vim plugin
replit/codemirror-vim pull request #48
Opened 2022-08-17 06:52 UTC by nightwing

fixes #46, #47

2022-10-04 20:24 UTC, lunaroyster reviewed
looks good to me, and fixes some major issues, thank you! 

i think @sergeichestakov or @masad-frost should provide the approving review since they understand the architecture better

2022-10-04 20:52 UTC, masad-frost approved these changes
:shipit:

2022-10-04 21:07 UTC, sergeichestakov requested changes
Thank you! This sounds reasonable but can we toggle the extension via an effect rather than using globals? See this example in the [CM docs](https://codemirror.net/examples/config/#private-compartments): 

<img width="731" alt="Screen Shot 2022-10-04 at 5 07 28 PM" src="https://user-images.githubusercontent.com/24947334/193928979-d2c488a6-949e-4e13-bcc9-f1317a0da33b.png">

2022-10-04 21:07 UTC, sergeichestakov commented on dev/index.ts
> +      key: "Alt-v",
why does `Alt-v` disable / enable Vim?

2022-10-04 21:07 UTC, sergeichestakov commented on dev/index.ts
> +let enableVim = true
can we dispatch an effect to toggle the extension from the compartment rather than relying on globals?

2022-10-05 20:45 UTC, masad-frost commented
@sergeichestakov this is just for the dev/example, i think using globals is fine there.

2022-10-05 21:05 UTC, sergeichestakov commented
Fair enough. Your call then! Might be nice to keep the example clean and according to best practices tho for others to get a better idea of how to use imo but no strong feelings

2022-10-05 21:05 UTC, sergeichestakov approved these changes

2022-10-06 13:07 UTC, merged